os:
 - osx

language: objective-c

env:
  matrix:
    - PYSMT_SOLVER="None" PYTHON_VERSION="2.7"
#    - PYSMT_SOLVER="z3" PYTHON_VERSION="2.7"
    - PYSMT_SOLVER="None" PYTHON_VERSION="3.4"
#    - PYSMT_SOLVER="z3" PYTHON_VERSION="3.4

before_install:
  - brew update
  - echo "Done"

install:
  - echo "Installing python..."
  # 2.7
  - if [ ${PYTHON_VERSION} == "2.7" ]; then brew install python;  fi
  - if [ ${PYTHON_VERSION} == "2.7" ]; then pip install six nose;  fi
  # 3.4
  - if [ ${PYTHON_VERSION} == "3.4" ]; then brew install python3; fi
  - if [ ${PYTHON_VERSION} == "3.4" ]; then pip3 install six nose; fi
  - source ./travis.sh

script:
  - env
  - python --version
  - if [ ${PYTHON_VERSION} == "2.7" ]; then python install.py --check;  fi
  - if [ ${PYTHON_VERSION} == "2.7" ]; then nosetests pysmt;  fi
  # 3.4
  - if [ ${PYTHON_VERSION} == "3.4" ]; then python3 install.py --check;  fi
  - if [ ${PYTHON_VERSION} == "3.4" ]; then nosetests3 pysmt;  fi
